


interface Viz {
render: any  //([callback]) 
active: ()=>{}  //([value]) 
aggs: object  //([value]) 
ariaHidden:   //([value]) 
backConfig:   //([value]) 
cache:   //([value]) 
color:   //([value]) 
colorScale:   //([value]) 
colorScaleConfig:   //([value]) 
colorScalePadding:   //([value]) 
colorScalePosition:   //([value]) 
colorScaleMaxSize:   //([value]) 
controls:   //([value]) 
controlConfig:   //([value]) 
controlPadding:   //([value]) 
data:   //(data, [formatter]) ↩︎
dataCutoff:   //([value]) 
depth:   //([value]) 
detectResize:   //(value)
detectResizeDelay:   //(value)
detectVisible:   //(value)
detectVisibleInterval:   //(value)
discrete:   //([value]) 
downloadButton:   //([value]) 
downloadConfig:   //([value]) 
downloadPosition:   //([value]) 
duration  //([ms]) 
filter:   //([value]) 
groupBy:   //([value]) 
height:   //([value]) 
hiddenColor:   //([value]) 
hiddenOpacity:   //([value]) 
hover:   //([value]) 
label:   //([value]) 
legend:   //([value]) 
legendConfig:   //([value]) 
legendCutoff:   //([value]) 
legendTooltip:   //([value]) 
legendPadding:   //([value]) 
legendPosition:   //([value]) 
legendSort:   //(value)
loadingHTML:   //([value]) 
loadingMessage:   //([value]) 
messageMask:   //([value]) 
messageStyle:   //([value]) 
noDataHTML:   //([value]) 
noDataMessage:   //([value]) 
scrollContainer:   //(selector)
select:   //([selector])
shape:   //([value]) 
shapeConfig:   //([value]) 
svgDesc:   //([value]) 
svgTitle:   //([value]) 
threshold:   //([value]) 
thresholdKey:   //([value]) 
thresholdName:   //([value]) 
time:   //([value]) 
timeFilter:   //([value]) 
timeline:   //([value]) 
timelineConfig:   //([value]) 
timelinePadding:   //([value]) 
title:   //([value]) 
titleConfig:   //([value]) 
titlePadding:   //([value]) 
tooltip:   //([value]) 
tooltipConfig:   //([value]) 
total:   //([value]) 
totalConfig:   //([value]) 
totalFormat:   //(value)
totalPadding:   //([value]) 
width:   //([value]) 
zoom:   //(value)
zoomBrushHandleSize:   //(value)
zoomBrushHandleStyle:   //(value)
zoomBrushSelectionStyle:   //(value)
zoomControlStyle:   //(value)
zoomControlStyleActive:   //(value)
zoomControlStyleHover:   //(value)
zoomFactor:   //(value)
zoomMax:   //(value)
zoomPan:   //(value)
zoomPadding:   //(value)
zoomScroll:   //([value]) 
}